# Generated by Django 3.2.13 on 2022-05-05 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gridprice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridprice',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 22, 25, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gridprice',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 22, 25, tzinfo=utc)),
        ),
    ]
