# Generated by Django 3.2.13 on 2022-04-23 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=31)),
                ('model', models.CharField(default='', max_length=31)),
                ('license_plate', models.CharField(default='', max_length=31)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.owner')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Charging', 'Charging'), ('Canceled', 'Canceled'), ('Success', 'Success'), ('Failure', 'Failure')], default='', max_length=31)),
                ('current_battery', models.DecimalField(decimal_places=4, default=-1, max_digits=8)),
                ('desired_final_batter', models.DecimalField(decimal_places=4, default=-1, max_digits=8)),
                ('charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargers.charger')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_arrival', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 0, 0, tzinfo=utc))),
                ('actual_arrival', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 0, 0, tzinfo=utc))),
                ('expected_departure', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 0, 0, tzinfo=utc))),
                ('actual_departure', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 0, 0, tzinfo=utc))),
                ('state', models.CharField(choices=[('Charging', 'Charging'), ('Canceled', 'Canceled'), ('Success', 'Success'), ('Failure', 'Failure')], default='', max_length=31)),
                ('price_per_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('parking_cost', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('parking_cost_extra', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('energy_cost', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargers.charger')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.vehicle')),
                ('vehicle_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.vehiclestate')),
            ],
        ),
    ]
