# Generated by Django 3.2.13 on 2022-05-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20220503_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='total_power_transmited',
            new_name='total_power_transmitted',
        ),
    ]
