# Generated by Django 3.2.13 on 2022-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_total_power_transmited_reservation_total_power_transmitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclestate',
            old_name='desired_final_batter',
            new_name='desired_final_battery',
        ),
        migrations.AddField(
            model_name='vehiclestate',
            name='energy_transmitted_so_far',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=8),
        ),
    ]
