# Generated by Django 3.2.13 on 2022-05-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20220503_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='total_power_transmitted',
            new_name='total_energy_transmitted',
        ),
    ]
