# Generated by Django 3.2.13 on 2022-05-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=63)),
                ('manufacturer', models.CharField(default='', max_length=63)),
                ('battery_capacity', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.model'),
        ),
    ]
