# Generated by Django 3.2.13 on 2022-04-23 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=31)),
                ('latitude', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('address', models.CharField(default='', max_length=63)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingCostSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=31)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('is_default', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_datetime', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 0, 0, tzinfo=utc))),
                ('to_datetime', models.DateTimeField(default=datetime.datetime(2022, 4, 23, 0, 0, tzinfo=utc))),
                ('parking_cost_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.parkingcostsnapshot')),
            ],
        ),
    ]
