# Generated by Django 3.2.13 on 2022-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_delete_pricinggroupstation'),
        ('stations', '0002_auto_20220423_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='pricing_groups',
            field=models.ManyToManyField(to='chargers.PricingGroup'),
        ),
    ]
