# Generated by Django 3.2.13 on 2022-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='operator status'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='owner status'),
        ),
    ]
