# Generated by Django 3.2.13 on 2022-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinggroup',
            name='name',
            field=models.CharField(default='', max_length=31),
        ),
    ]
