# Generated by Django 3.2.13 on 2022-04-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingGroupStation',
        ),
    ]
