# Generated by Django 3.2.13 on 2022-04-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_pricinggroup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charger',
            old_name='type',
            new_name='connector_type',
        ),
    ]
