# Generated by Django 3.2.13 on 2022-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_delete_pricinggroupstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
