# Generated by Django 3.2.13 on 2022-04-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('chargers', '0003_rename_type_charger_connector_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodConstantStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=31)),
                ('pricing_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_group', to='chargers.pricinggroup')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value', to='stations.station')),
            ],
        ),
        migrations.DeleteModel(
            name='MethodConstantPricingGroup',
        ),
    ]
