# Generated by Django 3.2.13 on 2022-05-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0004_auto_20220427_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='is_healthy',
            field=models.BooleanField(default=True),
        ),
    ]
